name: FujiNet PlatformIO CI

on:
  push:
    # Do not build tags. Do not build release branch
    branches:
      - "**"
      - "!release"
    tags:
      - "!**"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        target-platform: [ATARI, ADAM, APPLE]

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        pip install Jinja2
        pip install pyyaml
    - name: Show python version
      run: python --version
    - name: Show pio system info
      run: pio system info
    - name: Show pio location
      run: pip show platformio

    - name: Create INI ATARI for Build
      if: ${{ matrix.target-platform == 'ATARI' }}
      run: cp .github/workflows/platformio.ini.${{ matrix.target-platform }} platformio.ini

    - name: Create INI ADAM for Build
      if: ${{ matrix.target-platform == 'ADAM' }}
      run: cp .github/workflows/platformio.ini.${{ matrix.target-platform }} platformio.ini

    - name: Create INI APPLE for Build
      if: ${{ matrix.target-platform == 'APPLE' }}
      run: cp .github/workflows/platformio.ini.${{ matrix.target-platform }} platformio.ini

    - name: Show platformio.ini
      run: cat platformio.ini

    - name: Install espressif32 platform
      run: pio pkg install -p "platformio/espressif32"

    # Build filesystem first so it's available for zip file
    - name: ATARI Build Filesystem
      if: ${{ matrix.target-platform == 'ATARI' }}
      run: pio run -t buildfs -e fujinet-atari-v1

    - name: ADAM Build Filesystem
      if: ${{ matrix.target-platform == 'ADAM' }}
      run: pio run -t buildfs -e fujinet-adam-v1

    - name: APPLE Build Filesystem
      if: ${{ matrix.target-platform == 'APPLE' }}
      run: pio run -t buildfs -e fujiapple-rev0

    # Now build the firmware
    - name: ATARI Build
      if: ${{ matrix.target-platform == 'ATARI' }}
      run: pio run -e fujinet-atari-v1

    - name: ADAM Build
      if: ${{ matrix.target-platform == 'ADAM' }}
      run: pio run -e fujinet-adam-v1

    - name: APPLE Build
      if: ${{ matrix.target-platform == 'APPLE' }}
      run: pio run -e fujiapple-rev0

