name: FujiNet PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
        
    - name: Show Env
      run: python --version
      run: pio --version
      run: which pio
      
    - name: Create INI
      run: cp /home/runner/work/fujinet-platformio/fujinet-platformio/platformio-sample.ini /home/runner/work/fujinet-platformio/fujinet-platformio/platformio.ini

    - name: Select ATARI Build
      run: sed -i "s/^;\{0,1\}build_platform = BUILD_ATARI/build_platform = BUILD_ATARI/" /home/runner/work/fujinet-platformio/fujinet-platformio/platformio.ini

    - name: Fix up dirent.h
      run: awk '1;/#include <stdint.h>/{print "\n#ifdef __cplusplus\nextern "C" {\n#endif\n\n"}' /home/runner/work/.platformio/packages/framework-espidf/components/newlib/platform_include/sys/dirent.h
      run: echo '#ifdef __cplusplus\n}\n#endif\n' >> /home/runner/work/.platformio/packages/framework-espidf/components/newlib/platform_include/sys/dirent.h

    - name: Run PlatformIO
      run: pio run 
    - name: Build FS
      run: pio run -t buildfs
    - name: Show Directory
      run: ls -l
      
